- name: Make sure we have proper framebuffer depth
  lineinfile:
    dest: /boot/config.txt
    regexp: ^framebuffer_depth=
    line: framebuffer_depth=32

- name: Fix framebuffer bug
  lineinfile:
    dest: /boot/config.txt
    regexp: ^framebuffer_ignore_alpha=
    line: framebuffer_ignore_alpha=1

- name: Backup kernel boot args
  copy:
    src: /boot/cmdline.txt
    dest: /boot/cmdline.txt.orig
    force: no

- debug:
    msg: "Use cmdline.txt.orig for boot parameters (don't remove this file)"

- copy:
    src: /boot/cmdline.txt.orig
    dest: /boot/cmdline.txt
    force: yes

- name: Use Systemd as init and quiet boot process
  lineinfile:
    dest: /boot/cmdline.txt
    regexp: (.*)
    backrefs: yes
    line: \1 quiet init=/lib/systemd/systemd

- name: Install Cast viewer dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - console-data
    - libffi-dev
    - libssl-dev
    - matchbox
    - omxplayer
    - python-dev
    - python-netifaces
    - python-simplejson
    - rpi-update
    - systemd
    - chromium-browser
    - x11-xserver-utils
    - xserver-xorg

- name: Perform system upgrade
  apt:
    upgrade: dist
  tags:
    - system-upgrade

- name: Clean up unused packages
  command: apt-get -y autoremove
  tags:
    - system-upgrade

- name: Copy in rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    mode: 0755
    owner: root
    group: root

- name: Copy in 01_nodoc
  copy:
    src: 01_nodoc
    dest: /etc/dpkg/dpkg.cfg.d/01_nodoc
    mode: 0644
    owner: root
    group: root

- name: Copy in evdev
  copy:
    src: 10-evdev.conf
    dest: /usr/share/X11/xorg.conf.d/10-evdev.conf
    mode: 0644
    owner: root
    group: root

- name: Clear out X11 configs (disables touchpad and other unnecessary things)
  file:
    path: "/usr/share/X11/xorg.conf.d/{{ item }}"
    state: absent
  with_items:
    - 50-synaptics.conf
    - 10-quirks.conf
    - 50-wacom.conf

- name: Disable swap
  command: /sbin/swapoff --all removes=/var/swap

- name: Remove swapfile from disk
  file:
    path: /var/swap
    state: absent
