- name: Install Cast Viewer
  hosts: all
  user: pi
  become: yes

  handlers:
    - name: restart-cast-viewer
      command: systemctl restart cast-viewer.service
    - name: restart-ssh
      service: name=ssh state=restarted

  roles:
    - system
    - network
    - cast-viewer
    - splashscreen
